export const quotes = [
  "Live, laugh, love, repeat.",
  "Dream big, take action.",
  "Find beauty in everyday life.",
  "Love deeply, forgive freely.",
  "Embrace the present, cherish memories.",
  "Stay curious, never stop learning.",
  "Believe in yourself, achieve greatness.",
  "Create the life you desire.",
  "Kindness costs nothing, spreads joy.",
  "Success comes from perseverance.",
  "Be the reason someone smiles.",
  "Let your light shine bright.",
  "Live with passion and purpose.",
  "Choose happiness, spread positivity.",
  "Love yourself, embrace imperfections.",
  "Seek adventure, explore new horizons.",
  "Be the change you wish to see.",
  "Life is a beautiful journey.",
  "Follow your heart, trust yourself.",
  "Find joy in the ordinary.",
];
